# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"show": "00_core.ipynb",
         "ADC": "00_core.ipynb",
         "kurtosis": "00_core.ipynb",
         "SliceGroup": "00_core.ipynb",
         "DWIDataset": "00_core.ipynb",
         "get_ADC_map": "00_core.ipynb",
         "get_DK_map": "00_core.ipynb",
         "get_ADC_dataset": "00_core.ipynb",
         "get_DKI_dataset": "00_core.ipynb",
         "save_nii": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gkaissis.github.io/PyDWI/"

git_url = "https://github.com/gkaissis/PyDWI/tree/master/"

def custom_doc_links(name): return None
